config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  patch  '/login', to: 'users#edit'


  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 以下の行を追加
  resources :bases

  # get  '/user_attendances', to: 'attendances#update'
  get '/attendance_at_work', to: 'users#attendance_at_work'
  get '/update_attendance', to: 'users#update_attendance'
  #get '/correction', to: 'users#correction'

  resources :users do
    collection {post :import}
  
    member do
      #勤怠の基本情報編集
      get 'edit_basic_info'
      patch 'update_basic_info'
      #勤怠編集
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'

      get 'edit_overwork_request'
      patch 'edit_overwork_request_info'
      
       # 勤怠変更申請 保留
       get 'attendances/show_attendance_chg_req'

      get 'attendances/working'
      #残業申請
      get 'attendances/edit_overtime_application_req'
      patch 'attendances/update_overtime_application_req'
      #1ヶ月の勤怠承認
      get 'attendances/show_month_approval_req'


      #”勤怠変更申請者の勤怠確認
      get 'show_attendances_status_req'

      #”勤怠変更申請のお知らせ”のモーダル
      get 'attendances/show_change_modal'
      patch 'attendances/update_change_modal'

      #”残業申請のお知らせ”のモーダル
      get 'attendances/show_overtime_modal'
      patch 'attendances/update_overtime_modal'

      #”所属長承認申請のお知らせ”のモーダル
      #モーダルの表示
      get 'attendances/show_monthly_attendances_modal'
      #モーダルの中身
      patch 'attendances/update_monthly_attendances_modal'
      
      #1ヶ月分の勤怠申請
      patch 'attendances/send_monthly_attendance_request'
    end
    resources :attendances do
      member do
        patch 'update_overtime_application_req'
      end
  
      collection do
        # 勤怠修正ログ
        get 'search_log'
      end

      collection do
        # CSVエクスポート追加
        get 'export_csv'
      end
    end
    
    # 申請された上長ユーザー画面
    get 'attendances/edit_overtime_application_req'
    patch 'attendances/edit_overtime_applied_req'
    resources :attendances, only: :update
    resources :searches, only: :index
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :monthly_attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..50 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  self.per_page = 20

  # 既存のメソッド（digest, new_token, remember, authenticated?, forget, search）はそのまま維持

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user = find_by(email: row["email"]) || new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.password ||= SecureRandom.alphanumeric(8) # ランダムな8文字のパスワードを生成
      if user.save
        Rails.logger.info "User saved: #{user.attributes}"
      else
        Rails.logger.error "Failed to save user: #{user.email}, Errors: #{user.errors.full_messages.join(', ')}"
      end
    end
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin"]
  end
end

app/controllers/users/searches_controller.rb
class Users::SearchesController < ApplicationController
  def index
    @users = user.search(params[:keyword])
    @search_word = params[:keyword]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :show_attendances_status_req]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :edit_user]
  before_action :correct_user, only: [:edit]
  before_action :admin_or_correct_user, only: [:update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: [:show, :show_attendances_status_req]
  before_action :check_admin, only: [:update_attendance, :attendance_at_work, :index, :import]

    # システム管理権限所有かどうか判定します。
  def index
      # 基本のユーザー取得
      @users = User.all
    
      # 検索クエリがある場合はフィルタリング
      if params[:search].present?
        search_term = params[:search].downcase
        @users = @users.where('LOWER(name) LIKE ?', "%#{search_term}%")
      end
    
      # ページネーションの適用
      @users = @users.paginate(page: params[:page], per_page: 20)
    rescue
      flash.now[:danger] = "検索でエラーが発生しました。"
      @users = User.paginate(page: params[:page], per_page: 20)
  end
    

  def show
    @user = User.find(params[:id])
  
  # 管理者の場合はアクセス不可
  if current_user.admin?
    
    redirect_to(root_url) and return
  end

  # 上長または本人以外はアクセス不可
  unless current_user.superior? || current_user == @user
    flash[:danger] = "権限がありません"
    redirect_to(root_url) and return
  end
    @attendances = @user.attendances.where(worked_on: @first_day..@last_day)
    @worked_sum = @attendances.where.not(started_at: nil).count
    @attendance_chg_req_sum = Attendance.where(status: "申請中", overtime_instructor: @user.name).count
    @approval_req_sum = MonthlyAttendance.where(master_status: "申請中", instructor: @user.name).count
    @change_req_sum = Attendance.where(work_status: "申請中", work_instructor: @user.name).count
    @superiors = User.where(superior: true)
    @target_month = Date.current.month
    month = @first_day.month.to_s
    year  = @first_day.year.to_s
    @monthly_attendance = @user.monthly_attendances.where(month: month, year: year)

    return if current_user.admin? || current_user == @user
    flash[:danger] = "権限がありません"
    redirect_to(root_url)
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user.admin? || current_user == @user
  end
  
  def update
    @user = User.find(params[:id])
    if current_user.admin? || current_user == @user
      if @user.update(users_params)
        flash[:success] = "ユーザー情報を更新しました"
        redirect_to users_url
      else
        render :edit
      end
    else
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
    @user = User.find(params[:id])
  end

  def edit_one_month
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def import
    if params[:file].present?
      User.import(params[:file])
      flash[:success] = "CSVファイルのインポートが完了しました。"
    else
      flash[:danger] = "CSVファイルを選択してください。"
    end
    redirect_to users_url
  end
  
  def attendance_at_work
    today = Date.current  # または Date.today
    @users = User.joins(:attendances)
      .where(attendances: { worked_on: today })        # ① 今日の日付
      .where.not(attendances: { started_at: nil })    # ② 出勤済み
      .where(attendances: { finished_at: nil })       # ③ 未退勤
      .where.not(name: "Sample User")                 # Sample User以外
  end
  
  def update_attendance
  # ページだけ用意
  end
  
  def correction
  
  end

  def show_attendances_status_req
    @worked_sum = @attendances.where.not(started_at: nil).count
    @attendance_chg_req_sum = Attendance.where(status: "申請中",overtime_instructor: @user.name).count

  end

  def check_admin
    unless current_user&.admin?      # もし現在のユーザーが管理者でなければ
      flash[:danger] = "管理者権限が必要です"  # エラーメッセージを設定
      redirect_to root_path          # トップページに強制的に移動させる
    end
  end
  
  private

  def users_params
    params.require(:user).permit(:name, :email, :department, :employee_number, :uid, :password, :password_confirmation)
  end

  def basic_info_params
    params.require(:user).permit(:department, :basic_time, :work_time)
  end
  
  def attendances_params
    params.require(:user).permit(attendances: [:started_at, :finished_at])[:attendances]
  end
  
  def basic_work_time
    @a_finish_at -= @a_start_at 
  end
  
  def logged_in_user
     unless logged_in?
      flash[:danger] = "ログインしてください。"
      redirect_to login_url
     end 
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user) || current_user.admin?
  end
  
  def user_admin
    @users = User.paginate(page: params[:page], per_page: 20)
    if current_user.admin == false
      redirect_to root_path
    else
      render action: "index"
    end
  end
  
  def check_user_authorization
    user = User.find(params[:id])
    unless current_user.admin || current_user == user
      flash[:danger] = "権限がありません"
     redirect_to(root_url)
    end
  end
end

app/helpers/users/searches_helper.rb
module Users::SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :email, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :email, class: "form-control" %>
            
            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>
            
            <%= f.label :employeenumber, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :employeenumber, class: "form-control" %>
            
            <%= f.label :cardID, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :cardID, class: "form-control" %>
            
            <%= f.label :password, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :password, class: "form-control" %>
            
            <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :password_confirmation, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :指定勤務開始時間, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :started_at, class: "form-control" %>
            
            <%= f.label :指定勤務終了時間, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :finished_at, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/user_error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/attendance_at_work.html.erb
<!-- app/views/users/attendance_at_work.html.erb -->

<h1>出勤社員一覧</h1>
<table class="table table-bordered table-condensed base-table">
  <thead>
    <tr>
      <th>社員番号</th>
      <th>名前</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.employee_number %></td>
          <td><%= user.name %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<% if @users.empty? %>
  <p>現在出勤中の社員はいません。</p>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<%# index.html.erb %>
<% provide(:title, 'All Users') %>
<% provide(:button_text, '編集する') %>
<% if params[:search].blank? %>
  <h1>全てのユーザー覧</h1>
<% else %>
  <h1>検索結果</h1>
<% end %>

<div class=" col-md-10 col-md-offset-8">

<b>ユーザー名検索</b>

    <%= form_with url: users_path, method: :get, local: true do |f| %> <!--検索結果を表示したいurlの指定します-->
    <%= f.text_field :search %> <!--検索するワードを searchという架空のカラムに格納される-->
    <%= f.submit "検索",name: nil , class: "btn btn-primary" %>
  <% end %>
</div>

<%= form_with url: import_users_path do |form| %>
  <%= form.file_field :file, accept: 'text/csv' %>
  <%= form.submit "CSVインポート", class: "btn btn-primary" %>
<% end %>

<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
    <% @users.each do |user| %>
        <div class="user-name"><%= user.name %></div>
              <%= link_to "削除", user, method: :delete,data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>

            <div class="panel panel-default">
              <div class="panel-heading button-edit">
                <button class="btn btn-primary btn-lg" data-toggle="collapse" data-target="#collapse-<%= user.id %>">編集</button>
         </div>
                    <div class="collapse panel-body" id="collapse-<%= user.id%>">
                      <%= form_with(model: user, local: true) do |f| %>
                        <%= render 'shared/error_messages', object: user %>
                        <%= f.label :name, class: "label-#{yield(:class_text)}" %>
                        <p><%= user.name %></p>
                        <%= f.label :email, class: "label-#{yield(:class_text)}" %>
                        <%= f.text_field :email, class: "form-control" %>
                        <%= f.label :department, class: "label-#{yield(:class_text)}" %>
                        <%= f.text_field :department, class: "form-control" %>
                        <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
                        <%= f.text_field :employee_number, class: "form-control" %>
                        <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
                        <%= f.text_field :uid, class: "form-control" %>
                        <%= f.label :password, class: "label-#{yield(:class_text)}" %>
                        <%= f.password_field :password, class: "form-control" %>
                        <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
                        <%= f.password_field :password_confirmation, class: "form-control" %>
                        <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
                        <%= f.time_field :basic_time, class: "form-control" %>
                        <%= f.label :指定勤務開始時間, class: "label-#{yield(:class_text)}" %>
                        <%= f.time_field :started_at, class: "form-control" %>
                        <%= f.label :指定勤務終了時間, class: "label-#{yield(:class_text)}" %>
                        <%= f.time_field :finished_at, class: "form-control" %>
                        <div class="center">
                          <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}"%>
                          <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                            キャンセル
                          </button>
                        </div>
                      <% end %>
                    </div>
            </div>
    <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<%# show.html.erb %>
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td><%= link_to " ⇦ ", user_path(date: @first_day.prev_month), class: "btn btn-primary btn-attendance" %>
        <%= l(@first_day, format: :middle) %> 時間管理表
      <%= link_to " ⇨ ", user_path(date: @first_day.next_month), class: "btn btn-primary btn-attendance" %>
      </td>
      <td>指定勤務開始時間：<%= format_basic_info(@user.designated_work_start_time) %><br>
          指定勤務終了時間：<%= format_basic_info(@user.designated_work_end_time) %></td>
      <td  colspan="3">基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>コード</td>
      <td></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>月末日：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<% if current_user.superior %>
  <% if @approval_req_sum.present? && @approval_req_sum > 0 %>
    <%= link_to "【所属長承認申請のお知らせ】", attendances_show_monthly_attendances_modal_user_path, remote: true %>
    <span class="tsuuti"><%= @approval_req_sum %>件の通知があります。</span>
  <% else %>
    <span>【勤怠変更申請のお知らせ】</span>
  <% end %>
  <br/>
  
  <% if @change_req_sum.present? && @change_req_sum > 0 %>
    <%= link_to "【勤怠変更申請のお知らせ】", attendances_show_change_modal_user_path, remote: true %>
    <span class="tsuuti"><%= @change_req_sum %>件の通知があります。</span>
  <% else %>
    <span>【勤怠変更申請のお知らせ】</span>
  <% end %>
  <br/>
  
  <% if @attendance_chg_req_sum.present? && @attendance_chg_req_sum > 0 %>
    <%= link_to "【残業申請のお知らせ】", attendances_show_overtime_modal_user_path, remote: true %>
    <span class="tsuuti"><%= @attendance_chg_req_sum %>件の通知があります。</span>
  <% else %>
    <span>【残業申請のお知らせ】</span>
  <% end %>
  <br/>
  <br/>
<% end %>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-info" %>
  <%= link_to "CSV出力", export_csv_user_attendances_path(@user, date: @first_day), class: "btn btn-info" %>
  <%= link_to "勤怠修正ログ(承認済み)", search_log_user_attendances_path(@user, date: @first_day), class: "btn btn-info" %>
</div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>	
        <tr>
          <th rowspan="3">残業申請</th>
          <th rowspan="3">日付</th>
          <th rowspan="3">曜日</th>
          <th colspan="8">【実績】</th>
          <th colspan="5">【所定外勤務】</th>
        </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2" valign="bottom">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外残業</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認印</th>
      </tr>
     <tr>
      <th>時</th>
      <th>分</th>
      <th></th>
      <th>時</th>
      <th>分</th>
      <th></th>
      <th>時</th>
      <th>分</th>
     </tr>
    </thead>
    <tbody>
       <% @attendances.each do |day| %>
        <% css_class = 
          case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
          when '土'
            'text-primary'
          when '日'
            'text-danger'
          end
        %>
      <tr>
        <td><%= link_to "残業申請",attendances_edit_overtime_application_req_user_path(@user,date: day.worked_on),remote: true, class: "btn btn-primary" %></td>
        <td><%= l(day.worked_on, format: :short) %></td>
        <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
        <td><%= l(day.started_at.floor_to(15.minutes), format: :hour) if day.started_at.present? %></td>
        <td><%= l(day.started_at.floor_to(15.minutes), format: :min) if day.started_at.present? %></td>
        <td>
          <% btn_text = attendance_state(day) %>
          <% if btn_text == "出勤" %>
            <%= form_with(model: [@user, day], url: user_attendance_path(@user, day), method: :patch, local: true) do |f| %>
              <%= f.fields_for :attendance do |a| %>
                <%= a.hidden_field :started_at, value: Time.current %>
              <% end %>
              <%= f.submit "出勤登録", class: "btn btn-primary btn-attendance" %>
            <% end %>
          <% end %>
        </td>
        <td><%= l(day.finished_at.floor_to(15.minutes), format: :hour) if day.finished_at.present? %></td>
        <td><%= l(day.finished_at.floor_to(15.minutes), format: :min) if day.finished_at.present? %></td>
        <td>
          <% if btn_text == "退勤" %>
            <%= form_with(model: [@user, day], url: user_attendance_path(@user, day), method: :patch, local: true) do |f| %>
              <%= f.fields_for :attendance do |a| %>
                <%= a.hidden_field :finished_at, value: Time.current %>
              <% end %>
              <%= f.submit "退勤登録", class: "btn btn-primary btn-attendance" %>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
            <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
          <% end %>
        </td>
        <td><%= day.note %></td>
        <td><%= l(day.overtime.floor_to(15.minutes), format: :hour) if day.overtime.present? %></td>
        <td><%= l(day.overtime.floor_to(15.minutes), format: :min) if day.overtime.present? %></td>
        <td><% if day.overtime.present? %>
             <%= calc_overtime(day.overtime, @user.designated_work_end_time).round(2) %>
            <% end %>
        </td>
        <td><%= day.overtime_content.present? ? day.overtime_content : "-" %></td>
        <td><%= day.status.present? ? "#{day.overtime_instructor} に残業申請：#{day.status}<br>".html_safe : "" %>
            <%= day.work_status.present? ? "#{day.work_instructor} に勤怠変更申請：#{day.work_status}" : "" %></td>
      </tr>
    <% end %>
    </tbody>
    
    <tfoot>
      <%= form_with(model: @user, url: attendances_send_monthly_attendance_request_user_path(@user), method: :patch, local: true) do |f| %>
        
        <%= f.hidden_field :date, value: @first_day %>
        <tr>
          <td rowspan="2"></td>
          <td colspan="2">累計日数</td>
          <td colspan="2">総合勤務時間</td>
          <td colspan="2">累計在社時間</td>
          <td colspan="8"></td>
          <td>
            <% if @monthly_attendance.present? %>
            <% @monthly_attendance.each do |monthly_attendance| %>
              <% case monthly_attendance.master_status %>
              <% when '申請中' %>

                  所属長承認 <%= monthly_attendance.instructor %>へ申請中
              <% when '承認' %>
                所属長承認 <%= monthly_attendance.instructor %>から承認済
              <% when '否認' %>
                所属長承認 <%= monthly_attendance.instructor %>から否認
              <% else %>
                所属長承認 未
              <% end %>
             <% end %>
            <% else %>
              所属長承認 未
            <% end %>
            <% if @superiors.present? %>
            <%= f.collection_select :approval_instructor, @superiors, :name, :name, {include_blank: ""}, {required: true, class: "form-control"} %>
          <% end %>
            <%= f.submit "申請", class: "btn btn-primary btn-lg btn-block" %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="2"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="8"></td>
      </tr>
   </tfoot>
  </table>

  <div id="approval_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>
</div>

<div id="attendance_chg_req" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_overtime_application_req" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="show_change_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="show_overtime_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="show_monthly_attendances_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/update_attendance.html.erb
<h1>基本情報の更新</h1>