config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  patch  '/login', to: 'users#edit'


  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 以下の行を追加
  resources :bases

  # get  '/user_attendances', to: 'attendances#update'
  get '/attendance_at_work', to: 'users#attendance_at_work'
  get '/update_attendance', to: 'users#update_attendance'
  #get '/correction', to: 'users#correction'

  resources :users do
    collection {post :import}
  
    member do
      #勤怠の基本情報編集
      get 'edit_basic_info'
      patch 'update_basic_info'
      #勤怠編集
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'

      get 'edit_overwork_request'
      patch 'edit_overwork_request_info'
      
       # 勤怠変更申請 保留
       get 'attendances/show_attendance_chg_req'

      get 'attendances/working'
      #残業申請
      get 'attendances/edit_overtime_application_req'
      patch 'attendances/update_overtime_application_req'
      #1ヶ月の勤怠承認
      get 'attendances/show_month_approval_req'


      #”勤怠変更申請者の勤怠確認
      get 'show_attendances_status_req'

      #”勤怠変更申請のお知らせ”のモーダル
      get 'attendances/show_change_modal'
      patch 'attendances/update_change_modal'

      #”残業申請のお知らせ”のモーダル
      get 'attendances/show_overtime_modal'
      patch 'attendances/update_overtime_modal'

      #”所属長承認申請のお知らせ”のモーダル
      #モーダルの表示
      get 'attendances/show_monthly_attendances_modal'
      #モーダルの中身
      patch 'attendances/update_monthly_attendances_modal'
      
      #1ヶ月分の勤怠申請
      patch 'attendances/send_monthly_attendance_request'
    end
    resources :attendances do
      member do
        patch 'update_overtime_application_req'
      end
  
      collection do
        # 勤怠修正ログ
        get 'search_log'
      end

      collection do
        # CSVエクスポート追加
        get 'export_csv'
      end
    end
    
    # 申請された上長ユーザー画面
    get 'attendances/edit_overtime_application_req'
    patch 'attendances/edit_overtime_applied_req'
    resources :attendances, only: :update
    resources :searches, only: :index
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }

  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end

  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
  # 追加
  attribute :overtime, :datetime
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :show]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: :edit_one_month
  before_action :require_login # ログインしていないユーザーはアクセスできないようにする

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  # 出勤・退勤登録ボタン押下時の処理
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end

  # 勤怠編集ページの表示
  def edit_one_month
    @user = User.find(params[:id])
    @superiors = User.where(superior: true)
    @current_user = current_user # ログインしている上長
    @superiors = User.where(superior: true).where.not(id: @current_user.id) # ログイン中の上長を除外
    @attendances = Attendance.all
    @first_day = params[:date].to_date
    @last_day = @first_day.end_of_month
    @attendances = @user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
  end

  #勤怠編集ページの”編集を保存する”ボタン押下時の処理
  def update_one_month
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        @attendance = attendance
  
        # 指示者確認印が選択されている場合のみ処理を行う
        next unless item[:work_instructor].present?
  
        # 出社時間と退社時間の両方が入力されている場合
        if item[:started_at].present? && item[:finished_at].present?
          # 退社時間が出社時間以前の場合はエラーを返して処理を終了する
          if item[:finished_at] <= item[:started_at]
            flash[:danger] = "退社時間は出社時間より遅い時間を入力してください。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          else
            # 当日以降の勤怠は更新しない
            unless attendance.worked_on > Date.today
              # 勤怠変更情報を一時保存する
              attendance.chg_started_at = item[:started_at]
              attendance.chg_finished_at = item[:finished_at]
              attendance.note = item[:note]
              attendance.work_instructor = item[:work_instructor]
              attendance.work_status = "申請中"
              attendance.save!
            end
          end
        else
          # 出社時間または退社時間のどちらかが入力されていない場合
          flash[:danger] = "出社時間と退社時間の両方を入力してください。"
          redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
        end
      end
  
      flash[:success] = "勤怠変更を更新しました。"
      redirect_to user_url(date: params[:date])
    rescue ActiveRecord::RecordInvalid => e
      flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
      flash[:danger] += " #{e.message}" if e.message.present?
      redirect_to attendances_edit_one_month_user_url(date: params[:date])
    end
  end

  #勤怠変更申請　モーダル表示
  def show_change_modal
    @user = User.find(params[:id])
    @attendances = @user.attendances.where(work_status: "申請中").distinct
    @applicants = User.joins(:attendances).where(attendances: {work_status: "申請中", work_instructor: @user.name}).distinct
    @change_req_sum = @attendances.count
  end

  #勤怠変更申請　承認処理
  def update_change_modal
    apply_flg = false
    ActiveRecord::Base.transaction do
      attendance_change_params.each do |id, item|
        if item[:work_approval] == "1"
          attendance = Attendance.find(id)
          case item[:work_status]
          when "承認"
            if attendance.before_started_at.nil?
              attendance.before_started_at = attendance.started_at
            end
            if attendance.before_finished_at.nil?
              attendance.before_finished_at = attendance.finished_at
            end
            attendance.started_at = attendance.chg_started_at
            attendance.finished_at = attendance.chg_finished_at
            attendance.work_status = "承認"
            attendance.work_approval = "true"
            attendance.approval_date = Time.now
            apply_flg = true
          when "否認"
            attendance.work_status = "否認"
            attendance.work_approval = "true"
            apply_flg = true
          else
            # 何もしない
          end
          attendance.save!
        end
      end
    end

    if apply_flg
      flash[:success] = "勤怠変更申請について、指示者確認情報を更新しました。"
    else
      flash[:info] = "変更がありませんでした。"
    end
    redirect_to user_url
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効なデータがあったため、更新をキャンセルしました。"
    redirect_to user_url
  end

  #残業申請ボタン押下・表示
  def edit_overtime_application_req
    @user = User.find(params[:id])
    @attendance = @user.attendances.find_by(worked_on: params[:date])
    @date = params[:date].to_date
    @superiors = User.where(superior: true).where.not(name: @user.name)
  end
  
  #残業申請フォームの内容送信時の処理
  def update_overtime_application_req
    @user = User.find(params[:id])
    @attendance = Attendance.find_by(worked_on: params[:attendance][:date]&.to_date, user_id: @user.id)
    if @attendance
      @attendance.update(
        overtime: params[:attendance][:overtime],
        approval: params[:attendance][:approval],
        overtime_content: params[:attendance][:overtime_content],
        overtime_instructor: params[:attendance][:overtime_instructor],
        status: "申請中")
      flash[:success] = "残業申請を受け付けました。"
      redirect_to user_url
    else
      flash[:danger] = "勤怠データが見つかりません。"
      redirect_to user_url
    end
  end
  
  #残業申請のモーダル表示
  def show_overtime_modal
    @user = User.find(params[:id])
    @applicants = User.joins(:attendances).where(attendances: {status: "申請中", overtime_instructor: @user.name}).distinct
  end
  
  # 残業申請の承認処理
  def update_overtime_modal
    apply_flg = false
    ActiveRecord::Base.transaction do
      overtime_application_params.each do |id, item|
        if item[:approval] == "1"
          overtime_attendance = Attendance.find(id)
          case item[:status]
          when "承認"
            overtime_attendance.status = "承認"
            overtime_attendance.approval = true
            apply_flg = true
          when "否認", "なし"
            overtime_attendance.status = item[:status]
            overtime_attendance.approval = true
            apply_flg = true
          else
            # 何もしない
          end
          overtime_attendance.save!
        end
      end
    end

    if apply_flg
      flash[:success] = "残業申請について、指示者確認情報を更新しました。"
    else
      flash[:info] = "変更がありませんでした。"
    end
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効なデータがあったため、更新をキャンセルしました。"
    redirect_to user_url(date: params[:date])
  end

  #確認用の勤怠表示(残業申請・所属長承認申請・勤怠変更申請)
  # def show_attendances_status_req
  #   @applicant = User.find(params[:id])
  #   @attendances = @applicant.attendances.where(status: "申請中").distinct
  # end
  
  #1ヶ月分の勤怠申請処理
  def send_monthly_attendance_request
    @user = User.find(params[:id])
    @date = params[:user][:date].presence || Date.current
    @month = @date.to_date.month
    @year = @date.to_date.year
    monthly_attendance = MonthlyAttendance.find_or_create_by(user_id: @user.id, month: @month, year: @year)
    if monthly_attendance.persisted?
      monthly_attendance.instructor = params[:user][:approval_instructor]
      monthly_attendance.master_status = "申請中"
      monthly_attendance.save
      flash[:success] = "1ヶ月分の勤怠申請を送信しました。"
    else
      flash[:danger] = "1ヶ月の勤怠申請に失敗しました。"
    end
    redirect_to user_url(date: @date)
  end

  #所属長承認申請　モーダル表示
  def show_monthly_attendances_modal
    @user = User.find(params[:id])
    @applicants = User.joins(:monthly_attendances).where(monthly_attendances: {master_status: "申請中", instructor:@user.name}).distinct
  end
  
  #所属長承認申請　承認処理
  def update_monthly_attendances_modal
    @user = User.find(params[:id])
    apply_flg = false
    
    ActiveRecord::Base.transaction do
      show_monthly_attendances_modal_params.each do |id, item|
        if item[:approval] == "1"
          monthly_attendance = MonthlyAttendance.find(id)
          case item[:master_status]
          when "承認"
            monthly_attendance.master_status = "承認"
            monthly_attendance.approval = true
            apply_flg = true
          when "否認", "なし"
            monthly_attendance.master_status = item[:master_status]
            monthly_attendance.approval = true
            apply_flg = true
          else
            # 何もしない（"申請中"の場合）
          end
          monthly_attendance.save!
        end
      end
    end
  
    if apply_flg
      flash[:success] = "1ヶ月分の勤怠申請について、指示者確認情報を更新しました。"
    else
      flash[:info] = "変更がありませんでした。"
    end
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効なデータがあったため、更新をキャンセルしました。"
    redirect_to user_url(date: params[:date])
  end

  #勤怠修正ログ・変更履歴表示
  def search_log
    @user = User.find(params[:user_id]) # ユーザーを取得
  
    # 承認済みの勤怠情報を取得
    @attendance_logs = Attendance.where(user_id: @user.id).where.not(work_approval: nil)
  
    # 年月の検索パラメータがある場合、絞り込みを行う
    if params[:year].present? && params[:month].present?
      start_date = Date.new(params[:year].to_i, params[:month].to_i, 1)
      end_date = start_date.end_of_month
      @attendance_logs = @attendance_logs.where(worked_on: start_date..end_date)
    end
  
    @attendance_logs = @attendance_logs.order(worked_on: :desc)
  end

  def export_csv
    # 受け取った日付パラメータをDate型に変換
    target_date = Date.parse(params[:date])
    if params[:user_id].present?
      @user = User.find(params[:user_id])

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end

  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
end

app/views/attendances/_edit_overtime_application_req.html.erb
<!-- _edit_overtime_application_req.html.erb -->
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"></span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
<%= form_with(model: @attendance, url: attendances_update_overtime_application_req_user_path(@user), method: :patch, local: true) do |f| %>
      
          <h1 class= "modal-title">【勤怠残業申請】</h1>
            
            <table class= "table table-bordered table-striped">
             <thead>
              <tr>
                <th> 日付 </th>
                <th> 曜日 </th>
                <th> 終了予定時間 </th>
                <th> 翌日 </th>
                <th> 業務処理内容 </th>
                <th> 指示者確認㊞ </th>
              </tr>
             </thead>
             <tbody>
              <tr>
                <td><%= l(@date, format: :short) %></td>
                <%= f.hidden_field :date, :value => (@date) %>
                <td><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
                <td><%= f.time_field :overtime, required: true, class: "form-contcol modal-time" %></td>
                <td><%= f.check_box :approval, class: "form-contcol" %></td>
                <td><%= f.text_field :overtime_content, class: "form-contcol modal-note" %></td>
                <td><%= f.collection_select :overtime_instructor, @superiors, :name, :name, {include_blank: ""},{required: true, class: "form-control"} %></td>
              </tr>
             </tbody>
            </table>
          
        
      <%= f.submit "変更を送信する", class: "btn btn-primary btn-lg btn-block" %>
          
      <% end %>
       </div>
     </div>
   </div>
  </div>
</div>

app/views/attendances/_show_change_modal.html.erb
<!-- _show_change_modal.html.erb -->
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"></span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: attendances_update_change_modal_user_path(@user), method: :patch, local: true) do |f| %>
       <div class="center">
           <% @applicants.each do |applicant| %>
            <h3 class="modal-title">【<%= applicant.name %>からの勤怠変更申請】</h3>
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th rowspan="3">日付</th>
                  <th rowspan="3">曜日</th>
                  <th colspan="4">変更前</th>
                  <th colspan="4">変更後</th>
                  <th rowspan="3">備考</th>
                  <th rowspan="3">指示者確認㊞</th>
                  <th rowspan="3">変更</th>
                  <th rowspan="3">勤怠を確認する</th>
                </tr>
                <tr>
                  <th colspan="2">出社</th>
                  <th colspan="2">退社</th>
                  <th colspan="2">出社</th>
                  <th colspan="2">退社</th>
                </tr>
                <tr>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                </tr>
              </thead>
              <tbody>
                <% attendances = Attendance.where(user_id: applicant.id, work_status: "申請中", work_instructor: @user.name) %>
                <% attendances.each do |attendance| %>
                <%= f.fields_for "attendances[]", attendance do |i| %>
                <tr>
                  <td><%= l(attendance[:worked_on].to_date, format: :short) %></td>
                  <td><%= $days_of_the_week[attendance.worked_on.wday] %></td>
                  <td><%= attendance.started_at.strftime("%H") if attendance.started_at %></td>
                  <td><%= attendance.started_at.strftime("%M") if attendance.started_at %></td>
                  <td><%= attendance.finished_at.strftime("%H") if attendance.finished_at %></td>
                  <td><%= attendance.finished_at.strftime("%M") if attendance.finished_at %></td>
                  <!-- 変更後の出社時間（時間と分を表示） -->
                  <td><%= attendance.chg_started_at.present? ? attendance.chg_started_at.strftime("%H") : "-" %></td>
                  <td><%= attendance.chg_started_at.present? ? attendance.chg_started_at.strftime("%M") : "-" %></td>
                  <!-- 変更後の退社時間（時間と分を表示） -->
                  <td><%= attendance.chg_finished_at.present? ? attendance.chg_finished_at.strftime("%H") : "-" %></td>
                  <td><%= attendance.chg_finished_at.present? ? attendance.chg_finished_at.strftime("%M") : "-" %></td>
                  <td><%= attendance.note %></td>
                  <td><%= i.select :work_status, [["なし", "なし"], ["申請中", "申請中"], ["承認", "承認"], ["否認", "否認"]], { include_blank: true }, class: "form-control" %></td>
                  <td><%= i.check_box :work_approval, class: "form-control" %></td>
                  <td><%= link_to "確認", show_attendances_status_req_user_path(applicant.id, date: attendance.worked_on.beginning_of_month), class: "btn btn-primary btn-sm" %></td>
                </tr>
               <% end %>
              <% end %>
              </tbody>
            </table>
           <% end %>
           <%= f.submit "変更を送信する", class: "btn btn-primary btn-block" %>
          <% end %>
      </div> <!-- .center -->
    </div> <!-- .modal-body -->
  </div> <!-- .modal-content -->
</div> <!-- .modal-dialog -->

app/views/attendances/_show_monthly_attendances_modal.html.erb
<!-- _show_monthly_attendances_modal.html.erb -->
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="center">
        <%= form_with(model: @user, url: attendances_update_monthly_attendances_modal_user_path(@user), method: :patch, local: true) do |f| %>
          <% @applicants.each do |applicant| %>
            <h3 class="modal-title">【<%= applicant.name %>からの1ヶ月分勤怠申請】</h3>
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>年</th>
                  <th>月</th>
                  <th>指示者確認㊞</th>
                  <th>変更</th>
                  <th>勤怠を確認する</th>
                </tr>
              </thead>
              <tbody>
                <% monthly_attendances = MonthlyAttendance.where(user_id: applicant.id, master_status: "申請中", instructor: @user.name) %>
                <% monthly_attendances.each do |monthly_attendance| %>
                  <tr>
                    <td><%= monthly_attendance.year %></td>
                    <td><%= monthly_attendance.month %></td>
                    <%= f.fields_for "monthly_attendances[#{monthly_attendance.id}]", monthly_attendance do |i| %>
                      <td><%= i.select :master_status, [["なし", "なし"], ["申請中", "申請中"], ["承認", "承認"], ["否認", "否認"]], { include_blank: "" }, { required: true, class: "head_of_department_approval_modal" } %></td>
                      <td><%= i.check_box :approval %></td>
                      <% confirm_date = monthly_attendance.year + "-" + monthly_attendance.month + "-01 00:00" %>
                      <td><%= link_to "確認", show_attendances_status_req_user_path(applicant, monthly_attendance.id, date: confirm_date.to_datetime.beginning_of_month), class: "btn btn-primary btn-sm" %></td>
                      <%= i.hidden_field :id, value: monthly_attendance.id %>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
          <%= f.submit "変更を送信する", class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_show_overtime_modal.html.erb
<!-- _show_overtime_modal.html.erb -->
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="center">
        <%= form_with(model: @user, url: attendances_update_overtime_modal_user_path(@user), method: :patch, local: true) do |f| %>
         <% @applicants.each do |applicant| %>
          <h3 class="modal-title">【<%= applicant.name %>からの残業申請】</h3>
          <table class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>指定勤務終了時間</th>
                <th>時間外時間</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤務を確認する</th>
              </tr>
            </thead>
            <tbody>
                <% applicant.attendances.where(status: "申請中", overtime_instructor: @user.name).each do |attendance| %>
                <%= f.fields_for "attendances[]", attendance do |i| %>
                  <tr>
                    <td><%= l(attendance.worked_on.to_date, format: :short) %></td>
                    <td><%= $days_of_the_week[attendance.worked_on.wday] %></td>
                    <td><%= format_basic_info(attendance.overtime) %></td>
                    <td><%= format_basic_info(applicant.designated_work_end_time) %></td>
                    <td><%= format("%.2f", calc_overtime(attendance.overtime, applicant.designated_work_end_time)) %></td>
                    <td><%= attendance.overtime_content %></td>
                    <td><%= i.select :status, [["なし", "なし"],["申請中", "申請中"], ["承認", "承認"], ["否認", "否認"]], { include_blank: "" }, { required: true, class: "show_overtime_modal" } %></td>
                    <td><%= i.check_box :approval, class: "show_overtime_modal" %></td>
                    
                    <td><%= link_to "確認", show_attendances_status_req_user_path(applicant.id, date: attendance.worked_on.beginning_of_month), class: "btn btn-primary btn-sm" %></td>
                  </tr>
                <% end %>
                <% end %>
            </tbody>
          </table>
          <% end %>
          <%= f.submit "変更を送信する", class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_update_overtime_application_req.html.erb
<!-- update_overtime_application_req.html.erb -->

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">

          <% if @user.errors.any? %>
            <!-- エラーメッセージを表示 -->
            <div id="error_explanation">
              <div class="alert alert-danger">
                The form contains <%= pluralize(@user.errors.count, "error") %>.
              </div>
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <% if flash[:success] %>
            <!-- 成功メッセージを表示 -->
            <div class="alert alert-success">
              <%= flash[:success] %>
            </div>
          <% end %>

          <!-- 他の必要な情報や表示内容を追加 -->

        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/edit_one_month.html.erb
<%# edit_one_month.html.erb %>
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認㊞</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td><%= $days_of_the_week[day.worked_on.wday] %></td>
              <% if Date.current < day.worked_on %>
                <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :started_at, class: "form-control", value: day.started_at&.strftime("%H:%M") %></td>
                <td><%= attendance.time_field :finished_at, class: "form-control", value: day.finished_at&.strftime("%H:%M") %></td>
              <% end %>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at) %>
                <% end %>
              </td>
              <td><%= attendance.text_field :note, class: "form-control" %></td>
              <td>
                <%= attendance.collection_select :work_instructor, @superiors, :name, :name, include_blank: "選択して下さい", class: "form-control" %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>