config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  patch  '/login', to: 'users#edit'


  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 以下の行を追加
  resources :bases

  # get  '/user_attendances', to: 'attendances#update'
  get '/attendance_at_work', to: 'users#attendance_at_work'
  get '/update_attendance', to: 'users#update_attendance'
  #get '/correction', to: 'users#correction'

  resources :users do
    collection {post :import}
  
    member do
      #勤怠の基本情報編集
      get 'edit_basic_info'
      patch 'update_basic_info'
      #勤怠編集
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'

      get 'edit_overwork_request'
      patch 'edit_overwork_request_info'
      
       # 勤怠変更申請 保留
       get 'attendances/show_attendance_chg_req'

      get 'attendances/working'
      #残業申請
      get 'attendances/edit_overtime_application_req'
      patch 'attendances/update_overtime_application_req'
      #1ヶ月の勤怠承認
      get 'attendances/show_month_approval_req'


      #”勤怠変更申請者の勤怠確認
      get 'show_attendances_status_req'

      #”勤怠変更申請のお知らせ”のモーダル
      get 'attendances/show_change_modal'
      patch 'attendances/update_change_modal'

      #”残業申請のお知らせ”のモーダル
      get 'attendances/show_overtime_modal'
      patch 'attendances/update_overtime_modal'

      #”所属長承認申請のお知らせ”のモーダル
      #モーダルの表示
      get 'attendances/show_monthly_attendances_modal'
      #モーダルの中身
      patch 'attendances/update_monthly_attendances_modal'
      
      #1ヶ月分の勤怠申請
      patch 'attendances/send_monthly_attendance_request'
    end
    resources :attendances do
      member do
        patch 'update_overtime_application_req'
      end
  
      collection do
        # 勤怠修正ログ
        get 'search_log'
      end

      collection do
        # CSVエクスポート追加
        get 'export_csv'
      end
    end
    
    # 申請された上長ユーザー画面
    get 'attendances/edit_overtime_application_req'
    patch 'attendances/edit_overtime_applied_req'
    resources :attendances, only: :update
    resources :searches, only: :index
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠管理システム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
             <li><%= link_to "ユーザー一覧", users_path %></li>
             <li><%= link_to "出勤社員一覧", attendance_at_work_path %></li>
             <li><%= link_to "拠点情報の修正", bases_path %></li>
             <li><%= link_to "基本情報の更新", update_attendance_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">              
              <% if current_user.present? && current_user.admin == false %>
                <li><%= link_to "勤怠", current_user %></li>
                <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      
    </div>
  </body>
</html>